export const MESSAGE_TYPES = Object.freeze({
  // Content -> Background
  CONTENT_START_SESSION: 'CONTENT_START_SESSION',
  CONTENT_HUD_ACTION: 'CONTENT_HUD_ACTION',

  // Background -> Content
  BG_SESSION_UPDATE: 'BG_SESSION_UPDATE',
  BG_HUD_ERROR: 'BG_HUD_ERROR',

  // Background -> Offscreen
  OFFSCREEN_PLAY: 'OFFSCREEN_PLAY',
  OFFSCREEN_PAUSE: 'OFFSCREEN_PAUSE',
  OFFSCREEN_RESUME: 'OFFSCREEN_RESUME',
  OFFSCREEN_SEEK_REL: 'OFFSCREEN_SEEK_REL',
  OFFSCREEN_STOP: 'OFFSCREEN_STOP',

  // Offscreen -> Background
  OFFSCREEN_AUDIO_TIME: 'OFFSCREEN_AUDIO_TIME',
  OFFSCREEN_AUDIO_ENDED: 'OFFSCREEN_AUDIO_ENDED',
  OFFSCREEN_AUDIO_STATE: 'OFFSCREEN_AUDIO_STATE',
  OFFSCREEN_SEEK_UNDERFLOW: 'OFFSCREEN_SEEK_UNDERFLOW',
  OFFSCREEN_SEEK_OVERFLOW: 'OFFSCREEN_SEEK_OVERFLOW',
  OFFSCREEN_AUDIO_ERROR: 'OFFSCREEN_AUDIO_ERROR',
});

export const SESSION_STATUS = Object.freeze({
  IDLE: 'idle',
  LOADING: 'loading',
  PLAYING: 'playing',
  PAUSED: 'paused',
  STOPPED: 'stopped',
  ERROR: 'error',
  BLOCKED: 'blocked',
});

export const HUD_ACTION = Object.freeze({
  PREV: 'PREV',
  NEXT: 'NEXT',
  PAUSE: 'PAUSE',
  RESUME: 'RESUME',
  SEEK_REL: 'SEEK_REL',
  STOP: 'STOP',
});

export const SESSION_REASON = Object.freeze({
  SUPERSEDED_BY_NEW_TAB: 'superseded_by_new_tab',
  USER_STOPPED: 'user_stopped',
  QUEUE_ENDED: 'queue_ended',
  BUDGET_BLOCKED: 'budget_blocked',
  ERROR: 'error',
});

export const ERROR_CODE = Object.freeze({
  AUTH_ERROR: 'AUTH_ERROR',
  QUOTA_ERROR: 'QUOTA_ERROR',
  RATE_LIMIT: 'RATE_LIMIT',
  BAD_REQUEST: 'BAD_REQUEST',
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
  PARSE_ERROR: 'PARSE_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
});
